server:
   port: 9014

eureka:
  instance:
    virtualHostName: subscription
    appGroupName: LibertasViPaaS
    client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:7001}/eureka/
