server:
   port: 9006

eureka:
  instance:
    virtualHostName: entitlement
    appGroupName: LibertasViPaaS
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-server.credentials.uri:http://127.0.0.1:7001}/eureka/
    