package com.libertas.camel.component.braintree;

public enum Operation {
	RECURRING_PAYMENT_CREDITCARD,SIMPLE_PAYMENT_CREDITCARD, SAVE_CREDITCARD_PAYMENT, SIMPLE_PAYMENT_WITH_SAVED_CREDITCARD, DELETE_CREDITCARD
}